// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function Heartbeat() {
  return window['go']['main']['App']['Heartbeat']();
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadPackFile(arg1, arg2) {
  return window['go']['main']['App']['ReadPackFile'](arg1, arg2);
}

export function RefreshPacks() {
  return window['go']['main']['App']['RefreshPacks']();
}

export function SetClickThrough(arg1) {
  return window['go']['main']['App']['SetClickThrough'](arg1);
}
