// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {workshop} from '../models';

export function GetBootstrap():Promise<main.Bootstrap>;

export function Heartbeat():Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function ReadPackFile(arg1:string,arg2:string):Promise<string>;

export function RefreshPacks():Promise<Array<workshop.PackInfo>>;

export function SetClickThrough(arg1:boolean):Promise<void>;
